SET foreign_key_checks = 0;
TRUNCATE TABLE `providers`;

INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (1,'Mobleaders','mobleaders','https://mlrtds.com/?hash=0WX9npB3&land_id={send_id}&p1={hit_id}&p2={partner_id}-{source_id}&operator_id={operator_id}',1,NULL,1,1478009109,1547842260,'Mobleaders','{\"preland_add_param\":\"hard_add_preland=1\",\"preland_off_param\":\"hard_off_preland=1\",\"mobleaders_user_id\":\"309\",\"api_url\":\"http://billing.rgk.tools\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (2,'kz.rgkmobile.com','kpkz','http://rmobile-tds.com/-zFI9_NA2X/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1489752008,1517230466,'KP','{\"api_url\":\"http://kz.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (3,'by.rgkmobile.com','kpby','http://byrmobtds.com/WKQeuP2gOs/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1494856350,1517230460,'KP','{\"api_url\":\"http://by.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (4,'uae.rgkmobile.com','kpuae','http://uaermobtds.com/SKZUG34-TK/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1497971260,1517230453,'KP','{\"api_url\":\"http://uae.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (5,'rgkmobile.com','kpru','http://intechtds.com/q-Zv0iOCV9/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1500625682,1534335268,'KP','{\"api_url\":\"http://dashboard.rgkmobile.com\",\"hash\":\"66479c530ec5295dbfbf6fbf193ccc1e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (6,'eu.rgkmobile.com','kpeu','http://ermobtds.com/AN2YSqQwxl/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1507804744,1517230440,'KP','{\"api_url\":\"http://eu.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (7,'in.rgkmobile.com','kpin','http://inmobtds.com/OI3yqw4HKE/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1516892954,1517230435,'KP','{\"api_url\":\"http://in.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (8,'no.rgkmobile.com','kpno','http://normobtds.com/tLhWtHqv4-/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1521535956,1522296968,'KP','{\"api_url\":\"http://no.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (9,'ch.rgkmobile.com','kpch','http://chmobtds.com/Mjoe831hEx/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1522678481,1522678481,'KP','{\"api_url\":\"http://ch.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (10,'vn.rgkmobile.com','kpvn','http://appspace.vn/tds-redirect/hsDNQ_pJWV/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1527597584,1527597584,'KP','{\"api_url\":\"http://vn.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (11,'hn.rgkmobile.com','kphn','http://hnmobtds.com/p3-Z92DePM/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1534858742,1534859771,'KP','{\"api_url\":\"https://hn.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (12,'ni.rgkmobile.com','kpni','http://nimobtds.com/hFesHaFZm9/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1534859044,1534859777,'KP','{\"api_url\":\"https://ni.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (13,'gt.rgkmobile.com','kpgt','http://gtmobtds.com/9ObD_-l4Pw/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1534859062,1534859784,'KP','{\"api_url\":\"https://gt.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (14,'az.rgkmobile.com','kpaz','https://azmobtds.com/DOJSffOzMe/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1536155900,1536155900,'KP','{\"api_url\":\"https://az.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (15,'usd.rgkmobile.com','kpusd','http://urmobtds.com/YWlTshZzZE/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1543832442,1543832442,'KP','{\"api_url\":\"http://usd.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (16,'sa.rgkmobile.com','kpsa','http://samobtds.com/L7eug0gv-R/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1543930112,1543930112,'KP','{\"api_url\":\"https://sa.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\"}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (17,'iq.rgkmobile.com','kpiq','http://iqmobtds.com/w5HnmzlYwI/?landing_id={send_id}&operator_id={operator_id}&l1={hit_id}&l2={partner_id}-{source_id}',1,NULL,1,1551703560,1551712757,'KP','{\"api_url\":\"https://iq.rgkmobile.com\",\"hash\":\"d41d8cd98f00b204e9800998ecf8427e\",\"email\":\"wildo.click@rgkmobile.com\",\"language\":\"ru\",\"instanceId\":\"\",\"providerId\":null,\"streamId\":null}',NULL,1);
INSERT INTO `providers` (`id`,`name`,`code`,`url`,`status`,`redirect_to`,`created_by`,`created_at`,`updated_at`,`handler_class_name`,`settings`,`secret_key`,`is_rgk`) VALUES (18,'Bemobi','BMB','https://track.greentropolo.com/g/176990941b37216996?external_id={hit_id}&subpublisher_id={partner_id}',1,NULL,4,1553002895,1553007982,'Default','{\"custom_postback_status_on\":\"\",\"custom_postback_status_off\":\"\",\"custom_postback_status_onetime\":\"\",\"custom_postback_status_rebill\":\"\",\"custom_postback_status_complaint\":\"\",\"custom_postback_status_refund\":\"\"}','AhoOrHiyIzmhpQSbFBrEvWendpO-PXGN',0);

SET foreign_key_checks = 1;