<?php

namespace mcms\support;

class Module extends \mcms\common\module\Module
{
  public $controllerNamespace = 'mcms\support\controllers';

  const EVENT_SUPPORT_CREATED = 'event.support.created';
  const EVENT_SUPPORT_STATUS_CHANGED = 'event.support.status.changed';
  const EVENT_SUPPORT_DELEGATED = 'event.support.status.delegated';
  const EVENT_SUPPORT_MESSAGE_RECEIVED = 'event.support.message.received';
  const EVENT_SUPPORT_MESSAGE_SEND = 'event.support.message.send';

  const SETTINGS_EDIT_MESSAGE_TIME = 'support.settings.edit_message_time';

  public function __construct($id, $parent = null, $config = [])
  {
    parent::__construct($id, $parent, $config); // TODO: Change the autogenerated stub
  }


  public function init()
  {
    parent::init();
  }
}
