CREATE TABLE IF NOT EXISTS `statistic_user_{{userid}}` (
  revshare_ons                           mediumint(5) UNSIGNED           NULL,
  to_buyout_ons                          mediumint(5) UNSIGNED           NULL,
  rejected_ons                           mediumint(5) UNSIGNED           NULL,
  revshare_offs                          mediumint(5) UNSIGNED           NULL,
  rejected_offs                          mediumint(5) UNSIGNED           NULL,
  buyout_offs                            mediumint(5) UNSIGNED           NULL,
  revshare_offs24                        mediumint(5) UNSIGNED           NULL,
  rejected_offs24                        mediumint(5) UNSIGNED           NULL,
  buyout_offs24                          mediumint(5) UNSIGNED           NULL,
  revshare_rebills                       mediumint(5) UNSIGNED           NULL,
  rejected_rebills                       mediumint(5) UNSIGNED           NULL,
  buyout_rebills                         mediumint(5) UNSIGNED           NULL,
  revshare_rebills24                     mediumint(5) UNSIGNED           NULL,
  rejected_rebills24                     mediumint(5) UNSIGNED           NULL,
  buyout_rebills24                       mediumint(5) UNSIGNED           NULL,
  revshare_res_profit_rub                decimal(12, 5) UNSIGNED         NULL,
  revshare_res_profit_usd                decimal(12, 5) UNSIGNED         NULL,
  revshare_res_profit_eur                decimal(12, 5) UNSIGNED         NULL,
  rejected_res_profit_rub                decimal(12, 5) UNSIGNED         NULL,
  rejected_res_profit_usd                decimal(12, 5) UNSIGNED         NULL,
  rejected_res_profit_eur                decimal(12, 5) UNSIGNED         NULL,
  buyout_res_profit_rub                  decimal(12, 5) UNSIGNED         NULL,
  buyout_res_profit_usd                  decimal(12, 5) UNSIGNED         NULL,
  buyout_res_profit_eur                  decimal(12, 5) UNSIGNED         NULL,
  revshare_partner_profit_rub            decimal(12, 5) UNSIGNED         NULL,
  revshare_partner_profit_usd            decimal(12, 5) UNSIGNED         NULL,
  revshare_partner_profit_eur            decimal(12, 5) UNSIGNED         NULL,
  revshare_partner_profit24_rub          decimal(12, 5) UNSIGNED         NULL,
  revshare_partner_profit24_usd          decimal(12, 5) UNSIGNED         NULL,
  revshare_partner_profit24_eur          decimal(12, 5) UNSIGNED         NULL,
  rejected_partner_profit24_rub          decimal(12, 5) UNSIGNED         NULL,
  rejected_partner_profit24_usd          decimal(12, 5) UNSIGNED         NULL,
  rejected_partner_profit24_eur          decimal(12, 5) UNSIGNED         NULL,
  buyout_partner_profit24_rub            decimal(12, 5) UNSIGNED         NULL,
  buyout_partner_profit24_usd            decimal(12, 5) UNSIGNED         NULL,
  buyout_partner_profit24_eur            decimal(12, 5) UNSIGNED         NULL,
  revshare_res_ltv_profit_rub            decimal(12, 5) UNSIGNED         NULL,
  revshare_res_ltv_profit_usd            decimal(12, 5) UNSIGNED         NULL,
  revshare_res_ltv_profit_eur            decimal(12, 5) UNSIGNED         NULL,
  res_cpa_ltv_profit_rub                 decimal(12, 5) UNSIGNED         NULL,
  res_cpa_ltv_profit_usd                 decimal(12, 5) UNSIGNED         NULL,
  res_cpa_ltv_profit_eur                 decimal(12, 5) UNSIGNED         NULL,


  hits                                   mediumint(5) UNSIGNED           NULL,
  tb                                     mediumint(5) UNSIGNED           NULL,
  uniques                                mediumint(5) UNSIGNED           NULL,
  tb_uniques                             mediumint(5) UNSIGNED           NULL,
  to_buyout_hits                         mediumint(5) UNSIGNED           NULL,
  to_buyout_tb                           mediumint(5) UNSIGNED           NULL,
  to_buyout_uniques                      mediumint(5) UNSIGNED           NULL,
  to_buyout_tb_uniques                   mediumint(5) UNSIGNED           NULL,
  revshare_hits                          mediumint(5) UNSIGNED           NULL,
  revshare_tb                            mediumint(5) UNSIGNED           NULL,
  revshare_uniques                       mediumint(5) UNSIGNED           NULL,
  revshare_tb_uniques                    mediumint(5) UNSIGNED           NULL,
  otp_hits                               mediumint(5) UNSIGNED           NULL,
  otp_tb                                 mediumint(5) UNSIGNED           NULL,
  otp_uniques                            mediumint(5) UNSIGNED           NULL,
  otp_tb_uniques                         mediumint(5) UNSIGNED           NULL,

  revshare_text_complaints               mediumint(5) UNSIGNED           NULL,
  revshare_call_complaints               mediumint(5) UNSIGNED           NULL,
  revshare_call_mno_complaints           mediumint(5) UNSIGNED           NULL,
  otp_text_complaints                    mediumint(5) UNSIGNED           NULL,
  otp_call_complaints                    mediumint(5) UNSIGNED           NULL,
  otp_call_mno_complaints                mediumint(5) UNSIGNED           NULL,
  to_buyout_text_complaints              mediumint(5) UNSIGNED           NULL,
  to_buyout_call_complaints              mediumint(5) UNSIGNED           NULL,
  to_buyout_call_mno_complaints          mediumint(5) UNSIGNED           NULL,

  otp_ons                                mediumint(5) UNSIGNED           NULL,
  otp_visible_ons                        mediumint(5) UNSIGNED           NULL,
  otp_partner_profit_rub                 decimal(12, 5) UNSIGNED         NULL,
  otp_partner_profit_usd                 decimal(12, 5) UNSIGNED         NULL,
  otp_partner_profit_eur                 decimal(12, 5) UNSIGNED         NULL,
  otp_reseller_profit_rub                decimal(12, 5) UNSIGNED         NULL,
  otp_reseller_profit_usd                decimal(12, 5) UNSIGNED         NULL,
  otp_reseller_profit_eur                decimal(12, 5) UNSIGNED         NULL,
  otp_reseller_corrected_profit_rub      decimal(12, 5) UNSIGNED         NULL,
  otp_reseller_corrected_profit_usd      decimal(12, 5) UNSIGNED         NULL,
  otp_reseller_corrected_profit_eur      decimal(12, 5) UNSIGNED         NULL,

  buyout_ons                             mediumint(5) UNSIGNED           NULL,
  buyout_visible_ons                     mediumint(5) UNSIGNED           NULL,
  buyout_partner_profit_rub              decimal(12, 5) UNSIGNED         NULL,
  buyout_partner_profit_usd              decimal(12, 5) UNSIGNED         NULL,
  buyout_partner_profit_eur              decimal(12, 5) UNSIGNED         NULL,
  buyout_visible_price_rub               decimal(12, 5) UNSIGNED         NULL,
  buyout_visible_price_usd               decimal(12, 5) UNSIGNED         NULL,
  buyout_visible_price_eur               decimal(12, 5) UNSIGNED         NULL,
  buyout_price_rub                       decimal(12, 5) UNSIGNED         NULL,
  buyout_price_usd                       decimal(12, 5) UNSIGNED         NULL,
  buyout_price_eur                       decimal(12, 5) UNSIGNED         NULL,

  revshare_rgk_refunds                   mediumint(5) UNSIGNED           NULL,
  to_buyout_rgk_refunds                  mediumint(5) UNSIGNED           NULL,
  otp_rgk_refunds                        mediumint(5) UNSIGNED           NULL,
  revshare_mno_refunds                   mediumint(5) UNSIGNED           NULL,
  to_buyout_mno_refunds                  mediumint(5) UNSIGNED           NULL,
  otp_mno_refunds                        mediumint(5) UNSIGNED           NULL,
  revshare_rgk_refund_sum_rub            decimal(12, 5) UNSIGNED         NULL,
  revshare_rgk_refund_sum_usd            decimal(12, 5) UNSIGNED         NULL,
  revshare_rgk_refund_sum_eur            decimal(12, 5) UNSIGNED         NULL,
  to_buyout_rgk_refund_sum_rub           decimal(12, 5) UNSIGNED         NULL,
  to_buyout_rgk_refund_sum_usd           decimal(12, 5) UNSIGNED         NULL,
  to_buyout_rgk_refund_sum_eur           decimal(12, 5) UNSIGNED         NULL,
  otp_rgk_refund_sum_rub                 decimal(12, 5) UNSIGNED         NULL,
  otp_rgk_refund_sum_usd                 decimal(12, 5) UNSIGNED         NULL,
  otp_rgk_refund_sum_eur                 decimal(12, 5) UNSIGNED         NULL,
  revshare_mno_refund_sum_rub            decimal(12, 5) UNSIGNED         NULL,
  revshare_mno_refund_sum_usd            decimal(12, 5) UNSIGNED         NULL,
  revshare_mno_refund_sum_eur            decimal(12, 5) UNSIGNED         NULL,
  to_buyout_mno_refund_sum_rub           decimal(12, 5) UNSIGNED         NULL,
  to_buyout_mno_refund_sum_usd           decimal(12, 5) UNSIGNED         NULL,
  to_buyout_mno_refund_sum_eur           decimal(12, 5) UNSIGNED         NULL,
  otp_mno_refund_sum_rub                 decimal(12, 5) UNSIGNED         NULL,
  otp_mno_refund_sum_usd                 decimal(12, 5) UNSIGNED         NULL,
  otp_mno_refund_sum_eur                 decimal(12, 5) UNSIGNED         NULL,

  revshare_corrected_rebills             mediumint(5) UNSIGNED           NULL,
  revshare_corrected_reseller_profit_rub decimal(12, 5) UNSIGNED         NULL,
  revshare_corrected_reseller_profit_usd decimal(12, 5) UNSIGNED         NULL,
  revshare_corrected_reseller_profit_eur decimal(12, 5) UNSIGNED         NULL,
  revshare_corrected_rebills24           mediumint(5) UNSIGNED           NULL,

  date                                   date                            NOT NULL,
  hour                                   tinyint(1) UNSIGNED             NOT NULL,
  source_id                              mediumint(5) UNSIGNED DEFAULT 0 NOT NULL,
  landing_id                             mediumint(5) UNSIGNED DEFAULT 0 NOT NULL,
  operator_id                            mediumint(5) UNSIGNED DEFAULT 0 NOT NULL,
  platform_id                            mediumint(5) UNSIGNED DEFAULT 0 NOT NULL,
  landing_pay_type_id                    tinyint(1) UNSIGNED   DEFAULT 0 NOT NULL,
  is_fake                                tinyint(1) UNSIGNED   DEFAULT 0 NOT NULL,
  stream_id                              mediumint(5) UNSIGNED,
  country_id                             mediumint(5) UNSIGNED,
  provider_id                            mediumint(5) UNSIGNED,
  subid1_id                              bigint UNSIGNED       DEFAULT 0 NOT NULL,
  subid2_id                              bigint UNSIGNED       DEFAULT 0 NOT NULL,
  PRIMARY KEY (date, hour, source_id, landing_id, operator_id, platform_id, landing_pay_type_id, is_fake, subid1_id,
               subid2_id)
)
  COLLATE = utf8_unicode_ci;