set foreign_key_checks=0;
TRUNCATE TABLE `users`;
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (1, 'root', '', '$2y$13$i9V45Z.dT5lW4LaVR1X7lehov.BEOsdf/wv37aMbn3LYHN84Gp0Am', NULL, 'en', 'root@example.com', '', 0, 1527631526, 10, NULL, 1527197735, 1527631526, '', NULL, 0, NULL);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (2, 'admin', '', '$2y$13$CVgcKgX.vL980fQNg36oMe844pRgqywYInTMXiaiDCoxiQLousF8W', NULL, 'en', 'admin@example.com', NULL, 0, 0, 10, NULL, 1527197736, 1527197736, NULL, NULL, 0, NULL);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (3, 'partner', '', '$2y$13$ScuHeOMvPaIT10pkl6v8T.MfGPugfTf5SWV/CTRLzjMvWKWVJcteq', NULL, 'en', 'partner@example.com', '', 0, 1527536781, 10, NULL, 1527197737, 1527536781, '', NULL, 0, NULL);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (4, 'reseller', '', '$2y$13$uEyOXXrEHhGjzoQLvRDsEeOaw3DVnZsmfOgPtzWaMI9cjwMUE.9S6', NULL, 'en', 'reseller@example.com', NULL, 0, 0, 10, NULL, 1527197738, 1527197738, NULL, NULL, 0, NULL);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (5, 'investor-rub', '', '$2y$13$r/et9UB1iX.Ac4k6DxXhSOZ4L8UHBo8kMFYYQ/IVNJebPMf8JghLi', NULL, 'en', 'investor-rub@example.com', NULL, 0, 0, 7, NULL, 1527197739, 1527197739, NULL, NULL, 0, NULL);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (6, 'investor-usd', '', '$2y$13$OXww1KITDUmlsnk/u0dzYunbk4Urfz0sreXP8krYhoB6CL8xCcj.e', NULL, 'en', 'investor-usd@example.com', NULL, 0, 0, 7, NULL, 1527197740, 1527197740, NULL, NULL, 0, NULL);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (7, 'investor-eur', '', '$2y$13$UcKgmwsaqKgu0cRBiKWd2OtO7MbKyR2wlkpyGGY9xtU04WnoAG9AK', NULL, 'en', 'investor-eur@example.com', NULL, 0, 0, 7, NULL, 1527197741, 1527197741, NULL, NULL, 0, NULL);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (9, 'partner1', '', '$2y$13$ScuHeOMvPaIT10pkl6v8T.MfGPugfTf5SWV/CTRLzjMvWKWVJcteq', NULL, 'en', 'partner1@example.com', '', 0, 1527536781, 10, NULL, 1527197737, 1527536781, '', NULL, 0, 11);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (10, 'partner2', '', '$2y$13$ScuHeOMvPaIT10pkl6v8T.MfGPugfTf5SWV/CTRLzjMvWKWVJcteq', NULL, 'en', 'partner2@example.com', '', 0, 1527537069, 10, NULL, 1527197737, 1527537069, '', NULL, 0, 12);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (11, 'manager1@test.com', 'FZAAQzIaZB3pNw-2urdIl--KvC3HePFW', '$2y$13$S.LZKyqA2Zp7rot22/mSDeA0bYRpSJyXyjqVjr.eSIGV5cnCdvSkO', NULL, 'ru', 'manager1@test.com', '', 0, 0, 10, NULL, 1527629932, 1527629933, '', NULL, 0, NULL);
INSERT INTO `users` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `language`, `email`, `email_activation_code`, `is_online`, `online_at`, `status`, `login_attempts`, `created_at`, `updated_at`, `comment`, `access_token`, `token_expire`, `manager_id`) VALUES (12, 'manager2@test.com', '2n85gk3xN1mi0XX8cKb8jV7lwewKE8dY', '$2y$13$8C8azqYOwksgePd/FzDjPOCwiVEK.M88RRU0cF8RHLX3.rGiMvRDG', NULL, 'ru', 'manager2@test.com', '', 0, 0, 10, NULL, 1527629957, 1527629958, '', NULL, 0, NULL);

set foreign_key_checks=1;